import { useEffect, useState } from 'react';
import { Banknote, Building2, CalendarDays, ChevronLeft, IdCard, KeyRound, LayoutDashboard, LogOut, MapPin, Pencil, Plus, Save, School, UserPlus, UserRound, Users } from 'lucide-react';
import { authAPI, censeurAPI, comptabiliteAPI, directionAPI, platformAPI, secretariatAPI } from '../services/api';
import { PLATFORM_NAME } from '../config/branding';
import { generatePaymentReceiptPDF } from '../utils/paymentReceipt';

const labels = { directeur: 'Directeur', secretaire: 'Secrétaire', comptable: 'Comptable', censeur: 'Censeur' };
const money = (value) => `${Number(value || 0).toLocaleString('fr-FR')} F CFA`;
const blankStudent = { matricule: '', nom: '', prenom: '', sexe: '', date_naissance: '', lieu_naissance: '', nationalite: '', adresse: '' };
const classRank = (value = '') => { const level = value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, ''); const found = level.match(/(?:^|\s)(6|5|4|3)(?:e|eme)?|(?:^|\s)(2nde|2nd|seconde|1ere|1re|tle|terminale)/); const key = found?.[1] || found?.[2] || ''; return ({ 6: 1, 5: 2, 4: 3, 3: 4, '2nde': 5, '2nd': 5, seconde: 5, '1ere': 6, '1re': 6, tle: 7, terminale: 7 })[key] || 99; };
const sortClasses = (classes = []) => [...classes].sort((a, b) => { const rank = classRank(a.code_affichage) - classRank(b.code_affichage); return rank || a.code_affichage.localeCompare(b.code_affichage, 'fr', { numeric: true, sensitivity: 'base' }); });

export default function ManagementDashboard({ onLogout }) {
  const [user, setUser] = useState(null); const [section, setSection] = useState('tableau'); const [loading, setLoading] = useState(true);
  const [notice, setNotice] = useState(''); const [error, setError] = useState(''); const [profileEdit, setProfileEdit] = useState(false);
  const [profile, setProfile] = useState({ nom: '', prenom: '', email: '', telephone: '' }); const [password, setPassword] = useState({ currentPassword: '', newPassword: '', confirmPassword: '' });
  const [direction, setDirection] = useState(null); const [establishmentName, setEstablishmentName] = useState(''); const [secretaryClasses, setSecretaryClasses] = useState([]); const [censeurClasses, setCenseurClasses] = useState([]); const [classDetail, setClassDetail] = useState(null);
  const [cash, setCash] = useState(null); const [enrollOptions, setEnrollOptions] = useState(null); const [paymentOptions, setPaymentOptions] = useState([]); const [monitoring, setMonitoring] = useState(null); const [finance, setFinance] = useState(null);
  const [yearForm, setYearForm] = useState({ libelle: '', dateDebut: '', dateFin: '' }); const [siteForm, setSiteForm] = useState({ nom: '', adresse: '', commune: '', departement: '', telephone: '', email: '' }); const [classForm, setClassForm] = useState({ nom: '', divisionNom: '', divisionType: '' });
  const [editingStudent, setEditingStudent] = useState(null); const [transferStudent, setTransferStudent] = useState(null);
  const [enrollForm, setEnrollForm] = useState({ type: 'inscription', studentId: '', annualClassId: '', ...blankStudent });
  const refresh = async (role) => { if (role === 'directeur') setDirection((await directionAPI.overview()).data); if (role === 'secretaire') setSecretaryClasses((await secretariatAPI.listClasses()).data.classes); if (role === 'comptable') { const [cashData, enrollmentData, paymentData, financialConfiguration] = await Promise.all([comptabiliteAPI.cashOverview(), comptabiliteAPI.enrollmentOptions(), comptabiliteAPI.paymentOptions(), comptabiliteAPI.financialConfiguration()]); setCash(cashData.data); setEnrollOptions(enrollmentData.data); setPaymentOptions(paymentData.data.students); setFinance(financialConfiguration.data); } if (role === 'censeur') { setMonitoring((await censeurAPI.overview()).data); setCenseurClasses((await censeurAPI.listClasses()).data.classes); } };
  const loadClass = async (classId) => { try { const api = user.role === 'directeur' ? directionAPI : user.role === 'censeur' ? censeurAPI : secretariatAPI; setClassDetail((await api.listStudentsByClass(classId)).data); } catch { setError('Impossible de charger cette classe.'); } };
  useEffect(() => { authAPI.getMyProfile().then(async ({ data }) => { setUser(data.user); setProfile({ nom: data.user.nom || '', prenom: data.user.prenom || '', email: data.user.email || '', telephone: data.user.telephone || '' }); const [establishment] = await Promise.all([platformAPI.getEstablishment(), refresh(data.user.role)]); setEstablishmentName(establishment.data.etablissement?.nom || ''); }).catch(() => setError('Impossible de charger votre compte.')).finally(() => setLoading(false)); }, []);
  const action = async (work, success, after) => { setError(''); setNotice(''); try { await work(); await refresh(user.role); if (after) await after(); setNotice(success); } catch (err) { setError(err.response?.data?.error || 'Opération impossible.'); } };
  const saveProfile = (event) => { event.preventDefault(); action(async () => { const { data } = await authAPI.updateMyProfile(profile); setUser(data.user); sessionStorage.setItem('user', JSON.stringify(data.user)); setProfileEdit(false); }, 'Informations personnelles enregistrées.'); };
  const savePassword = (event) => { event.preventDefault(); action(async () => { await authAPI.changeMyPassword(password); setPassword({ currentPassword: '', newPassword: '', confirmPassword: '' }); setUser({ ...user, passwordPersonalized: true }); }, 'Mot de passe modifié.'); };
  const createYear = (event) => { event.preventDefault(); action(() => directionAPI.createFirstSchoolYear(yearForm), 'Année scolaire activée.'); };
  const createSite = (event) => { event.preventDefault(); action(() => directionAPI.createSite(siteForm), 'Nouveau site créé.', async () => setSiteForm({ nom: '', adresse: '', commune: '', departement: '', telephone: '', email: '' })); };
  const saveFinancialConfiguration = (payload) => action(() => comptabiliteAPI.saveFinancialConfiguration(payload), 'Configuration financière enregistrée.');
  const createClass = (event) => { event.preventDefault(); action(() => secretariatAPI.createClass(classForm), 'Classe annuelle créée.', async () => setClassForm({ nom: '', divisionNom: '', divisionType: '' })); };
  const updateStudent = (event) => { event.preventDefault(); action(() => secretariatAPI.updateStudent(editingStudent.id, editingStudent), 'Informations de l’élève mises à jour.', async () => { const id = classDetail.classInfo.id; setEditingStudent(null); await loadClass(id); }); };
  const moveStudent = (event) => { event.preventDefault(); action(() => secretariatAPI.transferStudent(transferStudent.id, transferStudent.destinationClassId), 'Transfert interne enregistré.', async () => { const id = classDetail.classInfo.id; setTransferStudent(null); await loadClass(id); }); };
  const createEnrollment = (event) => { event.preventDefault(); const payload = enrollForm.type === 'reinscription' ? { type: 'reinscription', studentId: enrollForm.studentId, annualClassId: enrollForm.annualClassId } : { ...enrollForm }; action(() => comptabiliteAPI.createEnrollment(payload), 'Inscription enregistrée. Les effectifs sont actualisés immédiatement.', async () => setEnrollForm({ type: 'inscription', studentId: '', annualClassId: '', ...blankStudent })); };
  const createPayment = async (payload) => { setError(''); setNotice(''); try { const { data } = await comptabiliteAPI.createPayment(payload); await generatePaymentReceiptPDF(data); await refresh(user.role); setNotice('Paiement enregistré. Le reçu interne a été téléchargé.'); } catch (err) { setError(err.response?.data?.error || 'Paiement impossible.'); } };
  if (loading) return <main className="min-h-screen grid place-items-center bg-slate-50 text-slate-500">Chargement…</main>;
  const content = section === 'profil' ? <Profile profile={profile} setProfile={setProfile} edit={profileEdit} setEdit={setProfileEdit} save={saveProfile} username={user.username}/> : section === 'securite' ? <Security password={password} setPassword={setPassword} save={savePassword}/> : <RoleContent {...{ role: user.role, section, direction, establishmentName, finance, saveFinancialConfiguration, secretaryClasses, censeurClasses, classDetail, loadClass, setClassDetail, classForm, setClassForm, createClass, yearForm, setYearForm, createYear, editingStudent, setEditingStudent, updateStudent, transferStudent, setTransferStudent, moveStudent, cash, enrollOptions, enrollForm, setEnrollForm, createEnrollment, paymentOptions, createPayment, monitoring }}/>; 
  return <div className="min-h-screen bg-[#f7faf8] flex"><aside className="hidden md:flex w-64 shrink-0 bg-white border-r border-slate-200 p-5 flex-col sticky top-0 h-screen"><div className="flex items-center gap-3"><div className="w-9 h-9 rounded-lg bg-emerald-600 flex items-center justify-center"><IdCard className="w-5 h-5 text-white"/></div><div><h1 className="text-lg font-semibold text-slate-800 leading-tight">{PLATFORM_NAME}</h1><p className="text-xs text-slate-500">Espace {labels[user.role]}</p></div></div><nav className="mt-9 space-y-1">{menu(user.role).map((item) => <button key={item.id} onClick={() => { setSection(item.id); setClassDetail(null); }} className={`w-full text-left flex items-center gap-3 px-3 py-3 rounded-lg text-sm transition ${section === item.id ? 'bg-emerald-50 text-emerald-700 font-medium' : 'text-slate-600 hover:bg-slate-100 hover:text-slate-900'}`}>{item.icon}{item.label}</button>)}</nav><button onClick={onLogout} className="mt-auto flex items-center gap-3 px-3 py-3 text-sm text-slate-600 hover:bg-slate-100 hover:text-slate-900 rounded-lg transition"><LogOut className="w-4"/>Déconnexion</button></aside><div className="flex-1 min-w-0"><header className="sticky top-0 z-30 bg-white border-b border-slate-200"><div className="max-w-7xl mx-auto px-4 sm:px-6 py-4 flex items-center justify-between"><div className="md:hidden flex items-center gap-3"><div className="w-9 h-9 rounded-lg bg-emerald-600 flex items-center justify-center"><IdCard className="w-5 h-5 text-white"/></div><div><h1 className="text-lg font-semibold text-slate-800">{PLATFORM_NAME}</h1><p className="text-xs text-slate-500">Espace {labels[user.role]}</p></div></div><p className="hidden md:block text-sm text-slate-500">{labels[user.role]}</p><button onClick={onLogout} className="md:hidden flex items-center gap-2 px-3 py-2 text-xs font-medium text-slate-600 hover:bg-slate-100 rounded-lg"><LogOut className="w-4"/>Déconnexion</button></div></header><nav className="md:hidden sticky top-[73px] z-20 bg-[#f7faf8] border-b border-slate-200"><div className="px-4 flex gap-1 overflow-x-auto">{menu(user.role).map((item) => <button key={item.id} onClick={() => { setSection(item.id); setClassDetail(null); }} className={`shrink-0 flex items-center gap-2 px-4 py-3 text-sm border-b-2 transition ${section === item.id ? 'border-emerald-600 text-emerald-700 font-medium' : 'border-transparent text-slate-500'}`}>{item.icon}{item.label}</button>)}</div></nav><main className="max-w-7xl mx-auto px-4 sm:px-6 py-8">{!user.passwordPersonalized && <Notice>Mot de passe initial encore actif : personnalisez-le dans « Sécurité ».</Notice>}{error && <Notice type="error">{error}</Notice>}{notice && <Notice type="success">{notice}</Notice>}<section>{content}</section></main></div></div>;
}

function menu(role) { const dashboard = { id: 'tableau', label: 'Tableau de bord', icon: <LayoutDashboard className="w-4"/> }; const profile = { id: 'profil', label: 'Informations personnelles', icon: <UserRound className="w-4"/> }; const security = { id: 'securite', label: 'Sécurité', icon: <KeyRound className="w-4"/> }; const items = { directeur: [], secretaire: [{ id: 'classes', label: 'Classes et élèves', icon: <School className="w-4"/> }], comptable: [{ id: 'inscriptions', label: 'Inscriptions', icon: <UserPlus className="w-4"/> }, { id: 'finances', label: 'Frais et tarifs', icon: <Banknote className="w-4"/> }, { id: 'caisse', label: 'Caisse', icon: <Banknote className="w-4"/> }], censeur: [{ id: 'classes', label: 'Classes et élèves', icon: <Users className="w-4"/> }] }; return [dashboard, ...items[role], profile, security]; }
function RoleContent(props) { if (props.role === 'directeur') return <DirectorHome {...props}/>; if (props.role === 'secretaire') return props.section === 'classes' ? <ClassRegistry {...props} editable/> : <SecretaryHome {...props}/>; if (props.role === 'comptable') return props.section === 'inscriptions' ? <Enroll {...props}/> : props.section === 'finances' ? <FinanceSettings {...props}/> : <Accountant {...props}/>; if (props.role === 'censeur') return props.section === 'classes' ? <ClassRegistry {...props}/> : <Monitoring {...props}/>; return null; }
function DirectorHome({ direction, yearForm, setYearForm, createYear, classDetail, setClassDetail, loadClass }) { const set = (key) => (e) => setYearForm({ ...yearForm, [key]: e.target.value }); const totalClasses = direction?.classes?.length || 0; const totalStudents = direction?.sites?.reduce((sum, site) => sum + Number(site.students_count || 0), 0) || 0; if (classDetail?.classInfo) return <ClassStudents editable={false} classes={direction?.classes || []} classDetail={classDetail} setClassDetail={setClassDetail}/>; return <><Title title="Tableau de bord" subtitle="Pilotage général de l’établissement"/><div className="grid grid-cols-2 lg:grid-cols-4 gap-4"><Card icon={<Building2/>} label="Établissement" value={direction?.etablissement?.nom || '—'}/><Card icon={<CalendarDays/>} label="Année active" value={direction?.anneeActive?.libelle || 'À configurer'}/><Card icon={<School/>} label="Classes actives" value={totalClasses}/><Card icon={<Users/>} label="Élèves inscrits" value={totalStudents}/></div>{!direction?.anneeActive && <Panel title="Lancer la première année scolaire"><form onSubmit={createYear} className="grid sm:grid-cols-3 gap-3"><Input label="Année scolaire" placeholder="2026-2027" value={yearForm.libelle} onChange={set('libelle')} required/><Input label="Début" type="date" value={yearForm.dateDebut} onChange={set('dateDebut')} required/><Input label="Fin" type="date" value={yearForm.dateFin} onChange={set('dateFin')} required/><button className="sm:col-span-3 primary">Activer l’année scolaire</button></form></Panel>}<Panel title="Classes de l’établissement"><div className="grid sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-5 gap-3">{direction?.classes?.length ? sortClasses(direction.classes).map((item) => <button key={item.id} onClick={() => loadClass(item.id)} className="text-left border border-slate-200 rounded-xl p-3 hover:border-emerald-500 hover:bg-emerald-50/30 transition"><p className="font-semibold text-slate-800 text-sm">{item.code_affichage}</p><p className="text-xs text-slate-500 mt-2">{item.effectif} élève(s)</p><p className="text-xs text-slate-400 mt-1 truncate">{item.site_nom}</p></button>) : <Empty>Aucune classe pour l’année active.</Empty>}</div></Panel></>; }
function Sites({ direction, siteForm, setSiteForm, createSite }) { const set = (key) => (event) => setSiteForm({ ...siteForm, [key]: event.target.value }); return <><Title title="Sites et filiales" subtitle="Le site principal est créé à l’installation. Ajoutez une filiale seulement si elle partage le même établissement."/><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4 mb-6">{direction?.sites?.map((site) => <Card key={site.id} icon={<MapPin/>} label={site.est_principal ? 'Site principal' : 'Filiale'} value={site.nom}><p className="text-xs text-slate-500 mt-3">{site.classes_count} classe(s) · {site.students_count} élève(s)</p></Card>)}</div><Panel title="Ajouter un site"><form onSubmit={createSite} className="grid sm:grid-cols-2 gap-3"><Input label="Nom du site" value={siteForm.nom} onChange={set('nom')} required/><Input label="Téléphone" value={siteForm.telephone} onChange={set('telephone')}/><Input label="Adresse" value={siteForm.adresse} onChange={set('adresse')}/><Input label="Commune" value={siteForm.commune} onChange={set('commune')}/><Input label="Département" value={siteForm.departement} onChange={set('departement')}/><Input label="Email" type="email" value={siteForm.email} onChange={set('email')}/><button className="sm:col-span-2 primary flex items-center justify-center gap-2"><Plus className="w-4"/>Créer le site</button></form></Panel></>; }
function FinanceSettings({ finance, saveFinancialConfiguration }) {
  const [draft, setDraft] = useState({ fees: [], plans: [] });
  useEffect(() => {
    if (!finance) return;
    setDraft({
      fees: finance.fees.map((fee) => ({ ...fee, applicableA: fee.applicable_a, montant: String(fee.montant) })),
      plans: finance.classes.map((annualClass) => ({ classeAnnuelleId: annualClass.id, label: annualClass.code_affichage, montantTotal: annualClass.plan ? String(annualClass.plan.montant_total) : '', tranches: annualClass.plan?.tranches?.map((tranche) => ({ ...tranche, montant: String(tranche.montant), dateEcheance: tranche.date_echeance })) || [] })),
    });
  }, [finance]);
  const setFee = (index, key, value) => setDraft({ ...draft, fees: draft.fees.map((fee, current) => current === index ? { ...fee, [key]: value } : fee) });
  const setPlan = (index, key, value) => setDraft({ ...draft, plans: draft.plans.map((plan, current) => current === index ? { ...plan, [key]: value } : plan) });
  const setTranche = (planIndex, trancheIndex, key, value) => setDraft({ ...draft, plans: draft.plans.map((plan, current) => current !== planIndex ? plan : { ...plan, tranches: plan.tranches.map((tranche, trancheCurrent) => trancheCurrent === trancheIndex ? { ...tranche, [key]: value } : tranche) }) });
  const addFee = () => setDraft({ ...draft, fees: [...draft.fees, { nom: '', montant: '', applicableA: 'les_deux', obligatoire: true, ordre: draft.fees.length, actif: true }] });
  const addTranche = (planIndex) => setDraft({ ...draft, plans: draft.plans.map((plan, current) => current !== planIndex ? plan : { ...plan, tranches: [...plan.tranches, { nom: `Tranche ${plan.tranches.length + 1}`, montant: '', dateEcheance: '', ordre: plan.tranches.length + 1, actif: true }] }) });
  const submit = (event) => { event.preventDefault(); saveFinancialConfiguration({ fees: draft.fees, plans: draft.plans }); };
  if (!finance?.year) return <><Title title="Paramètres financiers" subtitle="Configurez les frais et tarifs de l’année active"/><Empty>Activez d’abord une année scolaire.</Empty></>;
  return <><Title title="Paramètres financiers" subtitle={`Année ${finance.year.libelle} · ${finance.site.nom}`}/><form onSubmit={submit}><Panel title="Frais généraux" action={<button type="button" onClick={addFee} className="text-sm text-emerald-700">Ajouter un frais</button>}>{draft.fees.length ? draft.fees.map((fee, index) => <div key={fee.id || index} className="grid sm:grid-cols-4 gap-3 border-b pb-4 mb-4"><Input label="Libellé" value={fee.nom} onChange={(event) => setFee(index, 'nom', event.target.value)} required/><Input label="Montant (F CFA)" type="number" min="0" step="0.01" value={fee.montant} onChange={(event) => setFee(index, 'montant', event.target.value)} required/><label className="text-sm">Applicable à<select className="input" value={fee.applicableA} onChange={(event) => setFee(index, 'applicableA', event.target.value)}><option value="les_deux">Inscription et réinscription</option><option value="inscription">Inscription seulement</option><option value="reinscription">Réinscription seulement</option></select></label><label className="flex items-center gap-2 text-sm mt-6"><input type="checkbox" checked={fee.obligatoire} onChange={(event) => setFee(index, 'obligatoire', event.target.checked)}/> Obligatoire</label></div>) : <Empty>Aucun frais général configuré.</Empty>}</Panel><Panel title="Tarifs par classe"><div className="space-y-6">{draft.plans.length ? draft.plans.map((plan, planIndex) => <div key={plan.classeAnnuelleId} className="border rounded-lg p-4"><div className="grid sm:grid-cols-2 gap-3"><h4 className="font-medium">{plan.label}</h4><Input label="Tarif annuel (F CFA)" type="number" min="0.01" step="0.01" value={plan.montantTotal} onChange={(event) => setPlan(planIndex, 'montantTotal', event.target.value)} required/></div><div className="mt-4 space-y-3">{plan.tranches.map((tranche, trancheIndex) => <div key={tranche.id || trancheIndex} className="grid sm:grid-cols-4 gap-3"><Input label="Tranche" value={tranche.nom} onChange={(event) => setTranche(planIndex, trancheIndex, 'nom', event.target.value)} required/><Input label="Montant (F CFA)" type="number" min="0.01" step="0.01" value={tranche.montant} onChange={(event) => setTranche(planIndex, trancheIndex, 'montant', event.target.value)} required/><Input label="Échéance" type="date" value={tranche.dateEcheance} onChange={(event) => setTranche(planIndex, trancheIndex, 'dateEcheance', event.target.value)} required/><p className="text-xs text-slate-500 self-end pb-3">Les tranches doivent totaliser le tarif.</p></div>)}<button type="button" onClick={() => addTranche(planIndex)} className="text-sm text-emerald-700">Ajouter une tranche</button></div></div>) : <Empty>Créez d’abord une classe annuelle.</Empty>}</div></Panel><button className="primary">Enregistrer la configuration</button></form></>;
}
function SecretaryHome({ secretaryClasses }) { return <><Title title="Tableau de bord" subtitle="Classes et dossiers élèves"/><Card icon={<School/>} label="Classes annuelles" value={secretaryClasses.length}/><p className="text-sm text-slate-500 mt-6">Ouvrez « Classes et élèves » pour créer une classe ou consulter les élèves qui lui sont affectés.</p></>; }
function ClassRegistry({ editable, secretaryClasses, censeurClasses, classDetail, loadClass, setClassDetail, classForm, setClassForm, createClass, editingStudent, setEditingStudent, updateStudent, transferStudent, setTransferStudent, moveStudent, establishmentName }) {
  const classes = editable ? secretaryClasses : censeurClasses;
  const level = classForm.nom.trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/\s/g, '');
  const automaticType = ['6', '6e', '6eme', '5', '5e', '5eme', '4', '4e', '4eme'].includes(level) ? 'groupe' : ['2nde', '2nd', 'seconde', '1ere', '1re', 'tle', 'terminale'].includes(level) ? 'serie' : '';
  const isThird = ['3', '3e', '3eme'].includes(level);
  const divisionType = automaticType || classForm.divisionType;
  const divisionLabel = divisionType === 'groupe' ? 'Groupe' : divisionType === 'serie' ? 'Série' : 'Groupe ou série';
  const updateName = (nom) => {
    const normalized = nom.trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/\s/g, '');
    const automatic = ['6', '6e', '6eme', '5', '5e', '5eme', '4', '4e', '4eme'].includes(normalized) ? 'groupe' : ['2nde', '2nd', 'seconde', '1ere', '1re', 'tle', 'terminale'].includes(normalized) ? 'serie' : '';
    setClassForm({ ...classForm, nom, divisionType: ['3', '3e', '3eme'].includes(normalized) ? classForm.divisionType : automatic, divisionNom: ['3', '3e', '3eme'].includes(normalized) || automatic ? classForm.divisionNom : '' });
  };

  if (classDetail?.classInfo) return <ClassStudents {...{ editable, classes, classDetail, setClassDetail, editingStudent, setEditingStudent, updateStudent, transferStudent, setTransferStudent, moveStudent }}/>;

  return <>
    <Title title="Classes et élèves" subtitle={editable ? 'Créez une classe, puis ouvrez-la pour gérer les fiches élèves.' : 'Consultation des classes et des élèves.'}/>
    {editable && <Panel title="Créer une classe annuelle"><form onSubmit={createClass} className="grid sm:grid-cols-4 gap-3"><Input label="Classe" placeholder="6ème" value={classForm.nom} onChange={(e) => updateName(e.target.value)} required/>{automaticType && <Input label={divisionLabel} placeholder={automaticType === 'groupe' ? 'A' : 'D'} value={classForm.divisionNom} onChange={(e) => setClassForm({ ...classForm, divisionNom: e.target.value, divisionType: automaticType })}/>} {isThird && <><label className="text-sm">Type<select className="input" value={classForm.divisionType} onChange={(e) => setClassForm({ ...classForm, divisionType: e.target.value, divisionNom: '' })}><option value="">Choisir</option><option value="groupe">Groupe</option><option value="serie">Série</option></select></label><Input label={divisionLabel} placeholder="Valeur" value={classForm.divisionNom} onChange={(e) => setClassForm({ ...classForm, divisionNom: e.target.value })}/></>}<button className="primary self-end">Créer la classe</button></form>{automaticType && <p className="mt-3 text-xs text-slate-500">{automaticType === 'groupe' ? 'De la 6ème à la 4ème, la séparation est un groupe.' : 'De la 2nde à la Terminale, la séparation est une série.'}</p>}</Panel>}
    <div className="grid sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">{classes.length ? sortClasses(classes).map((item) => <button key={item.id} onClick={() => loadClass(item.id)} className="text-left min-h-36 bg-white border border-slate-200 rounded-2xl p-5 hover:border-emerald-500 hover:bg-emerald-50/30 transition"><h3 className="font-semibold text-base text-slate-800">{item.code_affichage}</h3><p className="text-sm text-slate-500 mt-5 flex items-center gap-2"><Users className="w-4 h-4"/>{item.effectif} élève(s)</p><p className="text-xs text-slate-400 mt-4 truncate">{establishmentName || item.site_nom || 'Établissement'}</p></button>) : <Empty>Aucune classe annuelle. Le directeur doit d’abord activer l’année scolaire.</Empty>}</div>
  </>;
}
function ClassStudents({ editable, classes, classDetail, setClassDetail, editingStudent, setEditingStudent, updateStudent, transferStudent, setTransferStudent, moveStudent }) {
  const students = classDetail.students || [];
  const setEdit = (key) => (e) => setEditingStudent({ ...editingStudent, [key]: e.target.value });
  const value = (item, fallback = 'Non renseigné') => item || fallback;

  return <>
    <button onClick={() => setClassDetail(null)} className="text-sm text-emerald-700 flex gap-1 mb-4"><ChevronLeft className="w-4"/>Retour aux classes</button>
    <Title title={classDetail.classInfo.code_affichage} subtitle={`${students.length} élève(s) affecté(s) à cette classe`}/>
    {editingStudent && <Panel title={`Modifier la fiche de ${editingStudent.nom} ${editingStudent.prenom}`} action={<button onClick={() => setEditingStudent(null)} className="text-sm">Annuler</button>}><form onSubmit={updateStudent} className="grid sm:grid-cols-2 gap-3"><Input label="Nom" value={editingStudent.nom || ''} onChange={setEdit('nom')} required/><Input label="Prénom" value={editingStudent.prenom || ''} onChange={setEdit('prenom')} required/><Input label="Date de naissance" type="date" value={editingStudent.date_naissance || ''} onChange={setEdit('date_naissance')}/><Input label="Lieu de naissance" value={editingStudent.lieu_naissance || ''} onChange={setEdit('lieu_naissance')}/><Input label="Nationalité" value={editingStudent.nationalite || ''} onChange={setEdit('nationalite')}/><Input label="Adresse" value={editingStudent.adresse || ''} onChange={setEdit('adresse')}/><Input label="Téléphone parent/tuteur" value={editingStudent.telephone || ''} onChange={setEdit('telephone')}/><label className="text-sm">Sexe<select value={editingStudent.sexe || ''} onChange={setEdit('sexe')} className="input"><option value="">Non renseigné</option><option value="M">Masculin</option><option value="F">Féminin</option></select></label><button className="sm:col-span-2 primary">Enregistrer les modifications</button></form></Panel>}
    {transferStudent && <Panel title={`Transférer ${transferStudent.nom} ${transferStudent.prenom}`} action={<button onClick={() => setTransferStudent(null)} className="text-sm">Annuler</button>}><form onSubmit={moveStudent} className="grid sm:grid-cols-2 gap-3"><label className="text-sm">Classe ou site de destination<select required className="input" value={transferStudent.destinationClassId || ''} onChange={(e) => setTransferStudent({ ...transferStudent, destinationClassId: e.target.value })}><option value="">Choisir</option>{classes.filter((c) => c.id !== classDetail.classInfo.id).map((c) => <option key={c.id} value={c.id}>{c.code_affichage}{c.site_nom ? ` — ${c.site_nom}` : ''}</option>)}</select></label><button className="primary self-end">Confirmer le transfert</button></form></Panel>}
    <Panel title="Liste des élèves">{students.length ? <div className="space-y-4">{students.map((student) => <article key={student.id} className="border border-slate-200 rounded-xl p-5 flex flex-col gap-4"><div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-3"><div><p className="font-semibold text-slate-800">{student.nom} {student.prenom}</p><p className="text-sm text-emerald-700 mt-1">Matricule : {value(student.matricule)}</p></div>{editable && <div className="flex gap-4 text-sm"><button onClick={() => setEditingStudent({ ...student })} className="text-emerald-700 flex items-center gap-1"><Pencil className="w-4"/>Modifier</button><button onClick={() => setTransferStudent({ ...student, destinationClassId: '' })} className="text-slate-700">Transférer</button></div>}</div><dl className="grid sm:grid-cols-2 lg:grid-cols-3 gap-x-6 gap-y-3 text-sm"><div><dt className="text-slate-400">Sexe</dt><dd>{value(student.sexe)}</dd></div><div><dt className="text-slate-400">Date de naissance</dt><dd>{value(student.date_naissance)}</dd></div><div><dt className="text-slate-400">Lieu de naissance</dt><dd>{value(student.lieu_naissance)}</dd></div><div><dt className="text-slate-400">Nationalité</dt><dd>{value(student.nationalite)}</dd></div><div><dt className="text-slate-400">Adresse</dt><dd>{value(student.adresse)}</dd></div><div><dt className="text-slate-400">Téléphone parent/tuteur</dt><dd>{value(student.telephone)}</dd></div></dl></article>)}</div> : <Empty>Aucun élève dans cette classe.</Empty>}</Panel>
  </>;
}
function Accountant({ cash, paymentOptions, createPayment }) {
  const [studentId, setStudentId] = useState('');
  const [modePaiement, setModePaiement] = useState('especes');
  const [montantRemis, setMontantRemis] = useState('');
  const [referencePaiement, setReferencePaiement] = useState('');
  const student = paymentOptions.find((item) => item.inscriptionId === studentId);
  const [allocations, setAllocations] = useState({});
  const total = Object.values(allocations).reduce((sum, value) => sum + Number(value || 0), 0);
  const setAllocation = (id, value) => setAllocations({ ...allocations, [id]: value });
  const submit = (event) => { event.preventDefault(); createPayment({ inscriptionId: studentId, modePaiement, montantRemis: modePaiement === 'especes' ? montantRemis : total, referencePaiement, allocations: Object.entries(allocations).filter(([, value]) => Number(value) > 0).map(([obligationId, montant]) => ({ obligationId, montant })) }); setAllocations({}); setMontantRemis(''); setReferencePaiement(''); };
  return <><Title title="Tableau de bord" subtitle="Caisse et inscriptions"/><div className="grid sm:grid-cols-3 gap-4"><Card icon={<Banknote/>} label="Encaissements du jour" value={money(cash?.today?.total)}/><Card icon={<Users/>} label="Inscriptions actives" value={cash?.enrolledStudents || 0}/><Card icon={<CalendarDays/>} label="Année active" value={cash?.activeYear?.libelle || 'Non configurée'}/></div><Panel title="Enregistrer un paiement"><form onSubmit={submit} className="space-y-5"><label className="block text-sm">Élève<select className="input" required value={studentId} onChange={(event) => { setStudentId(event.target.value); setAllocations({}); }}><option value="">Choisir un élève</option>{paymentOptions.map((item) => <option key={item.inscriptionId} value={item.inscriptionId}>{item.nom} {item.prenom} · {item.classe}</option>)}</select></label>{student && <><p className="text-sm text-slate-500">{student.matricule} · {student.classe}</p><div className="space-y-3">{student.obligations.filter((obligation) => obligation.reste > 0).map((obligation) => <div key={obligation.id} className="grid sm:grid-cols-3 gap-3 items-end border-b pb-3"><div><p className="text-sm font-medium">{obligation.libelle}</p><p className="text-xs text-slate-500">Reste : {money(obligation.reste)}{obligation.dateEcheance ? ` · Échéance ${obligation.dateEcheance}` : ''}</p></div><Input label="Montant à payer" type="number" min="0" max={obligation.reste} step="0.01" value={allocations[obligation.id] || ''} onChange={(event) => setAllocation(obligation.id, event.target.value)}/><p className="text-sm text-slate-600">{obligation.type === 'frais_general' ? 'Frais général' : 'Tranche'}</p></div>)}</div><p className="font-semibold">Total sélectionné : {money(total)}</p><label className="block text-sm">Moyen de paiement<select className="input" value={modePaiement} onChange={(event) => setModePaiement(event.target.value)}><option value="especes">Espèces</option><option value="mobilemoney_banque">Mobile Money / banque</option></select></label>{modePaiement === 'especes' && <Input label="Montant remis" type="number" min={total} step="0.01" value={montantRemis} onChange={(event) => setMontantRemis(event.target.value)} required/>}{modePaiement === 'mobilemoney_banque' && <Input label="Référence (facultative)" value={referencePaiement} onChange={(event) => setReferencePaiement(event.target.value)}/>}<button className="primary" disabled={!total}>Enregistrer le paiement et télécharger le reçu</button></>}</form></Panel></>;
}
function Enroll({ enrollOptions, enrollForm, setEnrollForm, createEnrollment }) { const isNew = enrollForm.type === 'inscription'; const set = (key) => (e) => setEnrollForm({ ...enrollForm, [key]: e.target.value }); return <><Title title="Inscriptions et réinscriptions" subtitle={enrollOptions?.year ? `Année ${enrollOptions.year.libelle}` : 'Aucune année active'}/><Panel title="Enregistrer une inscription">{!enrollOptions?.year ? <Empty>Le directeur doit activer l’année scolaire.</Empty> : !enrollOptions.classes.length ? <Empty>La secrétaire doit créer les classes annuelles.</Empty> : <form onSubmit={createEnrollment} className="grid sm:grid-cols-2 gap-3"><label className="text-sm">Opération<select className="input" value={enrollForm.type} onChange={set('type')}><option value="inscription">Nouvelle inscription</option><option value="reinscription">Réinscription</option></select></label><label className="text-sm">Classe<select required className="input" value={enrollForm.annualClassId} onChange={set('annualClassId')}><option value="">Choisir</option>{enrollOptions.classes.map((c) => <option key={c.id} value={c.id}>{c.code_affichage}</option>)}</select></label>{isNew ? <><Input label="Matricule national" value={enrollForm.matricule} onChange={set('matricule')} required/><Input label="Nom" value={enrollForm.nom} onChange={set('nom')} required/><Input label="Prénom" value={enrollForm.prenom} onChange={set('prenom')} required/><Input label="Date de naissance" type="date" value={enrollForm.date_naissance} onChange={set('date_naissance')}/><Input label="Lieu de naissance" value={enrollForm.lieu_naissance} onChange={set('lieu_naissance')}/><Input label="Nationalité" value={enrollForm.nationalite} onChange={set('nationalite')}/><Input label="Adresse et téléphone parent" value={enrollForm.adresse} onChange={set('adresse')}/><label className="text-sm">Sexe<select className="input" value={enrollForm.sexe} onChange={set('sexe')}><option value="">Non renseigné</option><option value="M">Masculin</option><option value="F">Féminin</option></select></label></> : <label className="text-sm sm:col-span-2">Élève déjà enregistré<select required className="input" value={enrollForm.studentId} onChange={set('studentId')}><option value="">Choisir</option>{enrollOptions.students.map((s) => <option key={s.id} value={s.id}>{s.matricule} — {s.nom} {s.prenom}</option>)}</select></label>}<button className="sm:col-span-2 primary">Valider l’opération</button></form>}</Panel></>; }
function Monitoring({ monitoring }) { return <><Title title="Tableau de bord" subtitle={monitoring?.activeYear ? `Suivi de l’année ${monitoring.activeYear.libelle}` : 'Aucune année active'}/><div className="grid sm:grid-cols-4 gap-4"><Card icon={<Users/>} label="Élèves actifs" value={monitoring?.totals?.actifs || 0}/><Card icon={<Users/>} label="Transferts" value={monitoring?.totals?.transferes || 0}/><Card icon={<Users/>} label="Renvois" value={monitoring?.totals?.renvoyes || 0}/><Card icon={<School/>} label="Classes" value={monitoring?.classes?.length || 0}/></div><p className="text-sm text-slate-500 mt-6">Ouvrez « Classes et élèves » pour consulter chaque classe. Le censeur ne modifie pas les informations élèves.</p></>; }
function Profile({ profile, setProfile, edit, setEdit, save, username }) { const set = (key) => (e) => setProfile({ ...profile, [key]: e.target.value }); return <><Title title="Informations personnelles" subtitle="Votre email sert à récupérer votre mot de passe"/>{!edit ? <Panel title="Mon profil" action={<button onClick={() => setEdit(true)} className="text-sm text-emerald-700">Modifier</button>}><dl className="grid sm:grid-cols-2 gap-5 text-sm"><Detail label="Identifiant" value={username}/><Detail label="Nom" value={profile.nom || '—'}/><Detail label="Prénom" value={profile.prenom || '—'}/><Detail label="Email" value={profile.email || '—'}/><Detail label="Téléphone" value={profile.telephone || '—'}/></dl></Panel> : <Panel title="Modifier mes informations"><form onSubmit={save} className="grid sm:grid-cols-2 gap-3"><Input label="Nom" value={profile.nom} onChange={set('nom')} required/><Input label="Prénom" value={profile.prenom} onChange={set('prenom')} required/><Input label="Email personnel" type="email" value={profile.email} onChange={set('email')}/><Input label="Téléphone" value={profile.telephone} onChange={set('telephone')}/><div className="sm:col-span-2 flex gap-3"><button className="primary flex gap-2"><Save className="w-4"/>Enregistrer</button><button type="button" onClick={() => setEdit(false)} className="text-sm px-3">Annuler</button></div></form></Panel>}</>; }
function Security({ password, setPassword, save }) { const set = (key) => (e) => setPassword({ ...password, [key]: e.target.value }); return <><Title title="Sécurité" subtitle="Modifiez votre mot de passe à tout moment"/><Panel title="Modifier mon mot de passe"><form onSubmit={save} className="grid sm:grid-cols-2 gap-3"><Input label="Mot de passe actuel" type="password" value={password.currentPassword} onChange={set('currentPassword')} required/><div/><Input label="Nouveau mot de passe" type="password" value={password.newPassword} onChange={set('newPassword')} required/><Input label="Confirmer le nouveau mot de passe" type="password" value={password.confirmPassword} onChange={set('confirmPassword')} required/><button className="sm:col-span-2 bg-slate-800 text-white rounded-lg p-2.5 text-sm">Modifier le mot de passe</button></form></Panel></>; }
function Title({ title, subtitle }) { return <div className="mb-6"><h2 className="text-2xl font-semibold">{title}</h2><p className="text-sm text-slate-500 mt-1">{subtitle}</p></div>; } function Panel({ title, action, children }) { return <section className="bg-white border rounded-xl p-6 mb-5"><div className="flex justify-between mb-5"><h3 className="font-semibold">{title}</h3>{action}</div>{children}</section>; } function Card({ icon, label, value, children }) { return <div className="bg-white border rounded-xl p-4"><div className="text-emerald-600 mb-3 w-5">{icon}</div><p className="text-xs text-slate-500">{label}</p><p className="font-semibold mt-1 truncate">{value}</p>{children}</div>; } function Input({ label, ...props }) { return <label className="block text-sm">{label}<input {...props} className="input"/></label>; } function Detail({ label, value }) { return <div><dt className="text-slate-500">{label}</dt><dd className="font-medium mt-1">{value}</dd></div>; } function Empty({ children }) { return <p className="text-sm text-slate-500">{children}</p>; } function Notice({ type = 'warning', children }) { const style = type === 'error' ? 'bg-rose-50 border-rose-200 text-rose-700' : type === 'success' ? 'bg-emerald-50 border-emerald-200 text-emerald-700' : 'bg-amber-50 border-amber-200 text-amber-800'; return <div className={`max-w-6xl mx-auto mb-5 p-4 border rounded-xl text-sm ${style}`}>{children}</div>; }
